---
- include: install.yml
  tags: install
  when: apt_cacher_ng_server is not defined
- include: configure.yml
  tags: configure
  when: apt_cacher_ng_server is not defined
- include: client.yml
  tags: client
  when: apt_cacher_ng_server is defined
